### ISSUE TITLE
Tom and Taha's code review

### ISSUE THREAD

**Issue by Taha-Hassan-Git** [fac27/AgencyWebsite#38]
### README

The why what and how of the project were clear from the readme

### User stories

User stories look good.

### Learning outcomes
Navigable with a keyboard, mobile layout is use-able. Media queries are good. 

Would be good to include CSS variables in the files. And a BEM naming convention, as well as comment it so it's easier to understand.

### UI bugs

The logo doesn't take you to the homepage as expect.

### Instructions

-

### File structure

File structure is a bit confusing to navigate.

### Flow of control

There's no JS so flow of control isn't relevant.

### Naming

There's no JS so flow of control isn't relevant.

### Readability

HTML, yes. Css not so readable.

**Comment by simonryrie** [comment]
Thank you for your feedback! I have created the following issues in response to your comments:

Use CSS variables for colours

Refactor and re-organise CSS

Logo link to take user to homepage

Re-organise file structure
