### ISSUE TITLE
Contact form reverts to two columns when viewport width goes below 250px

### ISSUE THREAD

**Issue by hanleymark** [fac27/AgencyWebsite#80]
When reducing viewport width, display changes from two column to single column for smaller screens. However at below 250px, the form display jumps back to two column layout.
[layout-issue.webm](https://user-images.githubusercontent.com/32879360/215557606-c8cba839-da63-432f-9670-e76f68618025.webm)

**Comment by shahryarrr** [comment]
Hi Mark,

Many thanks for pointing this.

I have now fixed this issue by updating one of the media queries.
